# Generated by Django 3.2.3 on 2021-08-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.FloatField(),
        ),
    ]
